//> using publish.name "scalacon-2022-demo"
//> using publish.repository "central-s01"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/alexarchambault/scalacon-2022-demo"
//> using publish.versionControl "github:alexarchambault/scalacon-2022-demo"
//> using publish.developer "Alex Archambault||https://github.com/alexarchambault"
